source "https://cdn.cocoapods.org/"

require_relative "../node_modules/react-native/scripts/react_native_pods"

platform :ios, "12.0"
install! "cocoapods", :integrate_targets => false

target "InkronikReactNativeCompatibility" do
  use_react_native!(
    :path => "../node_modules/react-native",
    :production => true,
    :hermes_enabled => false,
    :fabric_enabled => false
  )
  pod "InkronikReactNative", :path => "../node_modules/@inkronik/react-native"
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |configuration|
      configuration.build_settings["CLANG_CXX_LANGUAGE_STANDARD"] = "c++14"
      configuration.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "12.0"
      configuration.build_settings["OTHER_CPLUSPLUSFLAGS"] = "$(inherited) -Wno-error=deprecated-literal-operator -Wno-error=bitwise-instead-of-logical"

      next unless target.name == "RCT-Folly"

      definitions = Array(configuration.build_settings["GCC_PREPROCESSOR_DEFINITIONS"])
      configuration.build_settings["GCC_PREPROCESSOR_DEFINITIONS"] = definitions + ["$(inherited)", "FOLLY_HAVE_CLOCK_GETTIME=1"]
    end
  end
end
